### PR TITLE
ARGO-446 Refactor Ingestion due to attribute fix in messaging

### PR DESCRIPTION
**Pull request by kaggis**
## Issue
Due to change of attribute schema from array of objects to plain dictionary
{"key":"value",}
a change is needed accordingly to flume decoder interceptor in order to properly read the attribute dictionary and create the dedicated message headers.

## Implementation
- [x] Refactor extraction of attributes in decoder json
- [x] Update unit tests and docs
- [x] Change 'date' ingestion attribute to the more explanatory 'partition_date'

### CODE REVIEW

**Comment by kaggis** [comment]
please review 
/cc @themiszamani

**Comment by skanct** [comment]
@kaggis what is the partition date based on? On the time the message was received by flume, the time the results was received by the monitoring engine or the time the test was executed?

**Comment by kaggis** [comment]
@skanct the partition date is the date that the monitoring test was executed and it's used to select the proper destination folder at hdfs.

**Comment by skanct** [comment]
@kaggis can you mention this in the ingestion_dataflow.md?

**Comment by themiszamani** [comment]
+1

**Pull request merged**
