### PR TITLE
Refactor mongo clean scripts to include changes in aggr collections

### PR DESCRIPTION
**Pull request by kaggis**
One more PR to accompany the changes in 212.

Refactored mongo_clean_ar and mongo_clean_status py files to clean all the a/r and status collections with a loop 

please review
/cc @pkoro

### CODE REVIEW

**Comment by pkoro** [comment]
+1

**Comment by pkoro** [comment]
One question before merging. [Here][l1] do we need to add a report flag when calling the clean status script or is it not needed in the general case?

[l1]: https://github.com/ARGOeu/argo-compute-engine/blob/ARGO-146-Multitenancy/bin/job_status_detail.py#L108

**Comment by kaggis** [comment]
@pkoro indeed was missing, added support in the latest commit

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by skanct** [comment]
test this please

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by kaggis** [comment]
please review
/cc @dpavlos @pkoro @skanct

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
ok to test

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by skanct** [comment]
ok to test

**Comment by skanct** [comment]
test this please

**Comment by skanct** [comment]
test this please

**Comment by themiszamani** [comment]
retest this please

**Comment by themiszamani** [comment]
retest this please

**Comment by skanct** [comment]
retest this please

**Comment by themiszamani** [comment]
retest this please

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by pkoro** [comment]
+1

**Pull request merged**
