### PR TITLE
Sync deps

### PR DESCRIPTION
**Pull request by pkoro**
The new argo-egi-connectors package places sync files into another folder on the disk. This PR makes the location of this folder (where the connectors data are placed) configurable from within the CE configuration file. Multitenancy is preserved as this is covered through having within the sync folder several further subfolders (i.e. one per tenant).

### CODE REVIEW

**Comment by pkoro** [comment]
please review /cc @kaggis @skanct

**Comment by kaggis** [comment]
+1

**Comment by pkoro** [comment]
Sorry guys, I just discovered a few more compatibility issues. I'll post another review message after I resolve these as well.

**Comment by pkoro** [comment]
I believe this is reviewable again. I have tested the changed code on the standalone VM and everything seems to work with the new argo-connectors up to the API level. I would rather though we first merge #81 and only afterwards this one. 

please review /cc @skanct @kaggis

**Pull request merged**
