### PR TITLE
ARGO-155 Align CE output fields with new mongodb schema

### PR DESCRIPTION
**Pull request by kaggis**
- In this request the UDFs that prepare the data for output (such as GroupEndpointMap and ServiceMap) have been updated
 - Specifically the output tuple of the eval functions has been aligned with the fields expected in the mongodb schema
 - Accordingly the field names have been changed in the ouputSchema function of the udf

- Changes have been reflected also in the pig scripts. Alignment has been establish right before mongo_pig_connector writes the results to the datastore

- Same changes for the status details 

- Since now the fields have standard generic full blown names the mapping functionality (name->abbr) have been dropped from the code and from the configuration files

### CODE REVIEW

**Comment by kaggis** [comment]
Now opened anew against the multitenant branch 
please review
/cc @pkoro @dpavlos

**Comment by pkoro** [comment]
+1

**Comment by pkoro** [comment]
@kaggis as a first comment I think you should remove lines 26-28 and 80-83 from `utils.py` as the relevant section is scratched away from the configuration file. Also anything relating in the `utils_test.py` fie should be removed accordingly.

**Comment by pkoro** [comment]
Other than the comment above I don't have anything else to add. Let's discuss that one first and then we can merge.

**Comment by kaggis** [comment]
@pkoro. Indeed those paramaters are now deprecated, thanks for the catch! I removed them in the https://github.com/ARGOeu/argo-compute-engine/commit/039c1053da26e6a3aef8b7d3999d991b51d4abe3

**Pull request merged**
