### PR TITLE
[Proposed] ARGO-73 Poller further work (add executor call, unit tests)

### PR DESCRIPTION
**Pull request by kaggis**
I've fetched @dfolias branch with the latest changes from @makistsantekidis and opened a second pull request with some further changes.

- Regarding poller:
 - Added call to recomputation execution script (./recompute.py) using subprocess.Popen which doesn't block execution of poller
 - Re factored threshold check and moved it inside do_recomputation.
 - Now negative checks raise exceptions with appropriate msgs that are further handled and logged in main

- Regarding unit-tests:
 - Added mock to subprocess.pOpen and check for correct argument calls
 - Added unit test for successful run_recomputation
 - Added unit test for zero pending case. 
 - Added unit test for over threshold case
 
/cc please review 
@makistsantekidis @dpavlos @pkoro @skanct

### CODE REVIEW

**Comment by pkoro** [comment]
+1

tests again seem to run OK:

```
================================ test session starts =================================
platform darwin -- Python 2.7.6 -- py-1.4.28 -- pytest-2.7.1
rootdir: /Users/pkoro/Repositories/ar-compute-engine/bin, inifile: 
collected 3 items 

test_poller_ar.py ...

============================== 3 passed in 0.12 seconds ==============================
```

This PR overseeds #87 if I understand correctly, so before merging we should close that one.

**Comment by makistsantekidis** [comment]
+1 went through the changes and I agree with all of them

**Comment by dpavlos** [comment]
+1

**Comment by pkoro** [comment]
@kaggis please bump the spec version.

**Pull request closed without merging**
