### PR TITLE
ARGO-273 Replace conf files with generic  configuration templates

### PR DESCRIPTION
**Pull request by kaggis**
argo-compute-engine repo contains somewhat tenant specific conf files (`/conf`). They should be replaced with generic conf.template files (used for demonstration purposes).

- Remove unused parameters from conf files
- Replace values with generic ones 
- Remove old unused conf files

### CODE REVIEW

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by kaggis** [comment]
please review 
/cc @pkoro

**Comment by pkoro** [comment]
+1

**Comment by themiszamani** [comment]
test this please

**Pull request merged**
